name: Action Tmate
on:
  workflow_dispatch:
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup SSH Debug Session
        uses: mxschmitt/action-tmate@v3
